# Generated by Django 5.2.6 on 2025-09-23 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0003_usertrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_trips_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_users', to='yatra.trip'),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('started', models.BooleanField(default=False)),
                ('started_on', models.DateTimeField(null=True)),
                ('ended', models.BooleanField(default=False)),
                ('ended_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='yatra.trip')),
            ],
            options={
                'unique_together': {('name', 'trip')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out', models.BooleanField(default=False)),
                ('checked_out_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_users', to='yatra.activity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_activities_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['activity', 'checked_in'], name='yatra_usera_activit_493d54_idx')],
            },
        ),
    ]
