# Generated by Django 5.2.6 on 2025-09-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0005_bus_userbus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbus',
            name='checked_in_on',
            field=models.DateTimeField(null=True),
        ),
    ]
